print("\n")
print("Welcome to the Interactive Personal Data Collector !")
print("\n")
Name=input("Please enter your name:")
Age=int(input("Please enter your age:"))
Height=float(input("Please enter your height in meters:"))
FavNO=int(input("Please enter your favourite number:"))
year=2025-Age
print("\n")
print("Thank you ! Here is the information we collected :-")
print("\n")

print(f"Name: {Name} (Type: {type(Name)}, Memmory Address: {id(Name)})")
print(f"Age: {Age} (Type: {type(Age)}, Memmory Address: {id(Age)})")
print(f"Height: {Height} (Type: {type(Height)}, Memmory Address: {id(Height)})")
print(f"Favourite Number: {FavNO} (Type: {type(FavNO)}, Memmory Address: {id(FavNO)})")
print("\n")
print(f"Your birth year is approximately: {year} (based on your age of {Age})")
print("\n")
print("Thank you for using the Personal Data Collector. Goodbye !")